# logfile                       owner:group     mode    count   size    when    flags
~/Library/Logs/com.localbrain.api.out.log  700:700  600  7  1024  *  Z
~/Library/Logs/com.localbrain.api.err.log  700:700  600  7  1024  *  Z

