# logfile                       owner:group     mode    count   size    when    flags
__HOME__/Library/Logs/com.localbrain.api.out.log  __UID__:__GID__  600  7  1024  *  Z
__HOME__/Library/Logs/com.localbrain.api.err.log  __UID__:__GID__  600  7  1024  *  Z

