import os
import sys

import opentelemetry.exporter.prometheus
import psutil
from opentelemetry import metrics
from opentelemetry.exporter.prometheus import PrometheusMetricReader
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.resources import Resource
from prometheus_client import CollectorRegistry

# Get the current module object to check for existing variables (reload-safe)
_current_mod = sys.modules.get(__name__)

# Create or reuse the dedicated Prometheus registry for OpenTelemetry
if _current_mod and hasattr(_current_mod, "OTEL_REGISTRY"):
    OTEL_REGISTRY = _current_mod.OTEL_REGISTRY
else:
    OTEL_REGISTRY = CollectorRegistry()

# Monkeypatch the REGISTRY used by the OTel Prometheus reader to use our custom one.
opentelemetry.exporter.prometheus.REGISTRY = OTEL_REGISTRY

# Create or reuse the reader
if _current_mod and hasattr(_current_mod, "OTEL_METRICS_READER"):
    OTEL_METRICS_READER = _current_mod.OTEL_METRICS_READER
else:
    OTEL_METRICS_READER = PrometheusMetricReader()

# Create or reuse the provider
if _current_mod and hasattr(_current_mod, "provider"):
    provider = _current_mod.provider
else:
    provider = MeterProvider(
        resource=Resource.create({"service.name": "local-ai-brain"}),
        metric_readers=[OTEL_METRICS_READER],
    )

# In testing, we allow overriding the global meter provider to ensure
# that reloaded modules (and new readers) are properly registered.
if os.getenv("TESTING") == "1":
    from opentelemetry.metrics import _internal as otel_internal

    otel_internal._METER_PROVIDER = None
    otel_internal._METER_PROVIDER_SET_ONCE._done = False

metrics.set_meter_provider(provider)

# Create or reuse the meter
if _current_mod and hasattr(_current_mod, "meter"):
    meter = _current_mod.meter
else:
    meter = metrics.get_meter("local_ai_brain")


# Observable Gauges (Callbacks)
def get_process_memory(options):
    process = psutil.Process(os.getpid())
    return [metrics.Observation(process.memory_info().rss)]


def get_system_memory(options):
    return [metrics.Observation(psutil.virtual_memory().used)]


process_memory_used_bytes = meter.create_observable_gauge(
    "process_memory_used_bytes",
    callbacks=[get_process_memory],
    description="Current memory usage of the FastAPI process in bytes",
)
system_memory_used_bytes = meter.create_observable_gauge(
    "system_memory_used_bytes",
    callbacks=[get_system_memory],
    description="Current total system memory usage in bytes",
)

# UpDownCounters (Equivalent to Gauges with inc/dec)
if _current_mod and hasattr(_current_mod, "llm_active_requests"):
    llm_active_requests = _current_mod.llm_active_requests
else:
    llm_active_requests = meter.create_up_down_counter(
        "llm_active_requests",
        description="Number of LLM requests currently being processed",
    )

# Counters
if _current_mod and hasattr(_current_mod, "llm_tokens_consumed_total"):
    llm_tokens_consumed_total = _current_mod.llm_tokens_consumed_total
else:
    llm_tokens_consumed_total = meter.create_counter(
        "llm_tokens_consumed_total",
        description="Total number of prompt/input tokens consumed by the LLM",
    )

if _current_mod and hasattr(_current_mod, "llm_tokens_generated_total"):
    llm_tokens_generated_total = _current_mod.llm_tokens_generated_total
else:
    llm_tokens_generated_total = meter.create_counter(
        "llm_tokens_generated_total",
        description="Total number of completion/output tokens generated by the LLM",
    )

if _current_mod and hasattr(_current_mod, "memory_rejections_total"):
    memory_rejections_total = _current_mod.memory_rejections_total
else:
    memory_rejections_total = meter.create_counter(
        "memory_rejections_total",
        description="Total number of requests rejected due to memory limits",
    )

if _current_mod and hasattr(_current_mod, "http_requests_total"):
    http_requests_total = _current_mod.http_requests_total
else:
    http_requests_total = meter.create_counter(
        "http_requests_total",
        description="Total number of HTTP requests received",
    )

if _current_mod and hasattr(_current_mod, "tts_characters_processed_total"):
    tts_characters_processed_total = _current_mod.tts_characters_processed_total
else:
    tts_characters_processed_total = meter.create_counter(
        "tts_characters_processed_total",
        description="Total number of text characters processed by the TTS model",
    )

if _current_mod and hasattr(_current_mod, "stt_audio_seconds_transcribed_total"):
    stt_audio_seconds_transcribed_total = _current_mod.stt_audio_seconds_transcribed_total
else:
    stt_audio_seconds_transcribed_total = meter.create_counter(
        "stt_audio_seconds_transcribed_total",
        description="Total duration of audio in seconds processed by the STT model",
    )

# Histograms
if _current_mod and hasattr(_current_mod, "llm_generation_latency_seconds"):
    llm_generation_latency_seconds = _current_mod.llm_generation_latency_seconds
else:
    llm_generation_latency_seconds = meter.create_histogram(
        "llm_generation_latency_seconds",
        description="Latency of LLM text generation requests in seconds",
    )

if _current_mod and hasattr(_current_mod, "audio_processing_latency_seconds"):
    audio_processing_latency_seconds = _current_mod.audio_processing_latency_seconds
else:
    audio_processing_latency_seconds = meter.create_histogram(
        "audio_processing_latency_seconds",
        description="Latency of STT and TTS audio requests in seconds",
    )


def update_memory_metrics():
    """Legacy function maintained for compatibility; no-op with OTel observable gauges."""
    pass
