import os

import psutil
from opentelemetry import metrics
from opentelemetry.exporter.prometheus import PrometheusMetricReader
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.resources import Resource

# Create a Prometheus metrics reader (registers with prometheus_client)
OTEL_METRICS_READER = PrometheusMetricReader()

# Configure the MeterProvider with the Prometheus reader
provider = MeterProvider(
    resource=Resource.create({"service.name": "local-ai-brain"}),
    metric_readers=[OTEL_METRICS_READER],
)
metrics.set_meter_provider(provider)
meter = metrics.get_meter("local_ai_brain")


# Observable Gauges (Callbacks)
def get_process_memory(options):
    process = psutil.Process(os.getpid())
    return [metrics.Observation(process.memory_info().rss)]


def get_system_memory(options):
    return [metrics.Observation(psutil.virtual_memory().used)]


process_memory_used_bytes = meter.create_observable_gauge(
    "process_memory_used_bytes",
    callbacks=[get_process_memory],
    description="Current memory usage of the FastAPI process in bytes",
)
system_memory_used_bytes = meter.create_observable_gauge(
    "system_memory_used_bytes",
    callbacks=[get_system_memory],
    description="Current total system memory usage in bytes",
)

# UpDownCounters (Equivalent to Gauges with inc/dec)
llm_active_requests = meter.create_up_down_counter(
    "llm_active_requests",
    description="Number of LLM requests currently being processed",
)

# Counters
llm_tokens_consumed_total = meter.create_counter(
    "llm_tokens_consumed_total",
    description="Total number of prompt/input tokens consumed by the LLM",
)
llm_tokens_generated_total = meter.create_counter(
    "llm_tokens_generated_total",
    description="Total number of completion/output tokens generated by the LLM",
)
memory_rejections_total = meter.create_counter(
    "memory_rejections_total",
    description="Total number of requests rejected due to memory limits",
)
http_requests_total = meter.create_counter(
    "http_requests_total",
    description="Total number of HTTP requests received",
)
tts_characters_processed_total = meter.create_counter(
    "tts_characters_processed_total",
    description="Total number of text characters processed by the TTS model",
)
stt_audio_seconds_transcribed_total = meter.create_counter(
    "stt_audio_seconds_transcribed_total",
    description="Total duration of audio in seconds processed by the STT model",
)

# Histograms
llm_generation_latency_seconds = meter.create_histogram(
    "llm_generation_latency_seconds",
    description="Latency of LLM text generation requests in seconds",
)
audio_processing_latency_seconds = meter.create_histogram(
    "audio_processing_latency_seconds",
    description="Latency of STT and TTS audio requests in seconds",
)


def update_memory_metrics():
    """Legacy function maintained for compatibility; no-op with OTel observable gauges."""
    pass
