import os

import psutil
from prometheus_client import REGISTRY, Counter, Gauge, Histogram

# Unregister default collectors (GC, platform, process)
# We safely iterate over collectors and remove them
for collector in list(REGISTRY._names_to_collectors.values()):
    try:
        REGISTRY.unregister(collector)
    except (KeyError, ValueError):
        pass

# Gauges
process_memory_used_bytes = Gauge(
    "process_memory_used_bytes", "Current memory usage of the FastAPI process in bytes"
)
system_memory_used_bytes = Gauge(
    "system_memory_used_bytes", "Current total system memory usage in bytes"
)
llm_active_requests = Gauge(
    "llm_active_requests", "Number of LLM requests currently being processed"
)

# Counters
llm_tokens_consumed_total = Counter(
    "llm_tokens_consumed_total", "Total number of prompt/input tokens consumed by the LLM"
)
llm_tokens_generated_total = Counter(
    "llm_tokens_generated_total", "Total number of completion/output tokens generated by the LLM"
)
memory_rejections_total = Counter(
    "memory_rejections_total", "Total number of requests rejected due to memory limits"
)
http_requests_total = Counter(
    "http_requests_total", "Total number of HTTP requests received", ["endpoint", "status"]
)
tts_characters_processed_total = Counter(
    "tts_characters_processed_total", "Total number of text characters processed by the TTS model"
)
stt_audio_seconds_transcribed_total = Counter(
    "stt_audio_seconds_transcribed_total",
    "Total duration of audio in seconds processed by the STT model",
)

# Histograms
llm_generation_latency_seconds = Histogram(
    "llm_generation_latency_seconds", "Latency of LLM text generation requests in seconds"
)
audio_processing_latency_seconds = Histogram(
    "audio_processing_latency_seconds", "Latency of STT and TTS audio requests in seconds"
)


def update_memory_metrics():
    # Update process memory
    process = psutil.Process(os.getpid())
    process_memory_used_bytes.set(process.memory_info().rss)

    # Update system memory
    system_memory_used_bytes.set(psutil.virtual_memory().used)
