name: Auto Release

on:
  push:
    branches:
      - "main"
    paths:
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.12'

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(python -c '
          import tomllib
          with open("pyproject.toml", "rb") as f:
              version = tomllib.load(f)["project"]["version"]
          print(version)
          ')
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if Release Exists
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "v${{ steps.get_version.outputs.VERSION }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.get_version.outputs.VERSION }}" \
            --target "${{ github.sha }}" \
            --title "v${{ steps.get_version.outputs.VERSION }}" \
            --generate-notes
