name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@f98609f0fe30f4c5d3f05240fa93aa300bcacdbd # v5.3.0
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@321108471c997535887ad8995993436024593da0 # v5.4.0
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --frozen --all-extras --dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
